### ISSUE TITLE
Problem creating post without categories

### ISSUE THREAD

**Issue by juusechec** [bestmomo/laravel5-5-example#2]
Hello, i don't know how to create categories in interface, I want to create crud?

Thanks.

**Comment by bestmomo** [comment]
Hi
Administration does not manage categories, you can add them in base or add code to get this management, it's not so hard.

**Comment by bestmomo** [comment]
Categories management added with [this commit](https://github.com/bestmomo/laravel5-5-example/commit/83d2189b13efdcd46fb8dcad58926e6c27b0f6b4).

**Comment by juusechec** [comment]
Thanks!
