### ISSUE TITLE
Tags and keywords are not valid in Russian.

### ISSUE THREAD

**Issue by yuri25** [bestmomo/laravel5-5-example#24]
https://github.com/EamonKeane/laravel5-5-example/blob/master/app/Http/Requests/PostRequest.php
`  $regex = '/^[A-Za-z0-9-éèàù]{1,50}?(,[A-Za-z0-9-éèàù]{1,50})*$/';`

Is the problem in this expression or does something need to be fixed yet? Help me please.

**Comment by bestmomo** [comment]
Hi,
I think it's is this regex, you should add russian specific characters.

**Comment by yuri25** [comment]
I did this:
$regex = '/^[A-Za-z0-9-А-Яа-я0-9]{1,50}?(,[A-Za-z0-9-А-Яа-я0-9]{1,50})*$/';

All the same does not pass validation ....
What do you need more or what actions to take?
And what do these symbols in general mean - éèàù

**Comment by yuri25** [comment]
Also does not help this kind of:
`$regex = '/^[A-Za-z0-9А-Яа-я]{1,50}?(,[A-Za-z0-9А-Яа-я]{1,50})*$/';`

**Comment by bestmomo** [comment]
Look at [this question](https://stackoverflow.com/questions/1716609/how-to-match-cyrillic-characters-with-a-regular-expression) for Regex Russian Cyrillic class management.

**Comment by yuri25** [comment]
I brought to this form: 
`$regex = '/^[\p{L}zA-Z0-9]{1,50}?(,[\p{L}zA-Z0-9]{1,50})*$/';`
Probably you need to change files somewhere else ... But where?
![tagskey](https://user-images.githubusercontent.com/253228/38457891-0b415090-3a9f-11e8-8bdb-97191dd746c1.jpg)

**Comment by bestmomo** [comment]
This regex is the only place for tag validation, you can check this if you remove regex rule. So your class must be wrong.

**Comment by yuri25** [comment]
The problem with tags is solved, the expression works fine. 
` $regex = '/^[\p{L}zA-Z0-9]{1,50}?(,[\p{L}zA-Z0-9]{1,50})*$/u';`  - Working.
When posting a post, the problem of the image remained unresolved ...

Intervention \ Image \ Exception \ NotReadableException
Unable to init from given url (http://youwo.ru/\files/yandex_2.jpg).
Rights to the folder changed several times and the owners also changed - nothing helps: (
Why is such a strange URL `(http://youwo.ru/\files/yandex_2.jpg)`
`..../vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php`

```
   83     throw new \Intervention\Image\Exception\NotReadableException(
   84        "Unable to init from given url (".$url.")."
```

**Comment by yuri25** [comment]
It seems to me that the path to the image is being formed incorrectly and because of this an error appears ...  Whence the backslash?
![screenshot 4](https://user-images.githubusercontent.com/253228/38473607-4bdda084-3b9b-11e8-8d42-bec77447938e.png)

**Comment by yuri25** [comment]
If I manually change the backslash on a line, then this error is missing and the publication is successful. Look, please, where to fix, so that the backslash does not appear. Every time manually correcting it on a straight line is not good ...
![screenshot 5](https://user-images.githubusercontent.com/253228/38473735-62d6442e-3b9d-11e8-968c-37ec815224ab.png)

**Comment by yuri25** [comment]
What do you think about this error? `Unable to init from given url (http://youwo.ru/\files/yandex_2.jpg).`

**Comment by yuri25** [comment]
Error found here:
/...../resources/views/back/posts/template.blade.php

```
222        function processSelectedFile(filePath, requestingField) {
223            $('#' + requestingField).val('\\' + filePath)
224            $('#img').attr('src', '\\' + filePath)
225           }
```
It is necessary to change slashes as follows:

```
222        function processSelectedFile(filePath, requestingField) {
223            $('#' + requestingField).val('\/' + filePath)
224            $('#img').attr('src', '\/' + filePath)
225           }
```

Now this error has been fixed.
