### ISSUE TITLE
Error creating user

### ISSUE THREAD

**Issue by diouck** [bestmomo/laravel5-5-example#25]
Hello I'm trying your code. I had this error to create a new user
Do you have an idea?
And how to configure the pase word regeneration?
Thank you
<code>
"""
SQLSTATE[23502]: Not null violation: 7 ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « role »\n
DETAIL:  La ligne en échec contient (26, 2018-06-06 15:07:21, 2018-06-06 15:07:21, Abdou DIOUCK, diouckk@hotmail.com, $2y$10$qOqocB4ogniFU1zHMEV0teJOQVKxneCi5/2c12Zhel4ZozB9WFvgq, null, null, f, f, null) (SQL: insert into "users" ("name", "email", "password", "updated_at", "created_at") values (Abdou DIOUCK, diouckk@hotmail.com, $2y$10$qOqocB4ogniFU1zHMEV0teJOQVKxneCi5/2c12Zhel4ZozB9WFvgq, 2018-06-06 15:07:21, 2018-06-06 15:07:21) returning "id")
</code>
 
"""
SQLSTATE[23502]: Not null violation: 7 ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « role »\n
DETAIL:  La ligne en échec contient (26, 2018-06-06 15:07:21, 2018-06-06 15:07:21, Abdou DIOUCK, diouckk@hotmail.com, $2y$10$qOqocB4ogniFU1zHMEV0teJOQVKxneCi5/2c12Zhel4ZozB9WFvgq, null, null, f, f, null) (SQL: insert into "users" ("name", "email", "password", "updated_at", "created_at") values (Abdou DIOUCK, diouckk@hotmail.com, $2y$10$qOqocB4ogniFU1zHMEV0teJOQVKxneCi5/2c12Zhel4ZozB9WFvgq, 2018-06-06 15:07:21, 2018-06-06 15:07:21) returning "id")

**Comment by bestmomo** [comment]
Hi,
I dont get this issue. With MySQL "if an ENUM column is declared NOT NULL, its default value is the first element of the list of permitted values". So it's "user" for this application.

**Comment by diouck** [comment]
In fact the problem comes from the column role that should not be null Can be put by default user?

**Comment by bestmomo** [comment]
You can add default in users table migration.

**Comment by diouck** [comment]
Ok i have desactived role 
Now i have this error
<code>
ErrorException (E_WARNING)
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
</code>

**Comment by bestmomo** [comment]
Hello,
It's another issue, you use **https** and certificate is not valid.

**Comment by diouck** [comment]
I tried but it gives nothing. The problem is that the confirmation email is not sent. how do you configure the mail?

**Comment by diouck** [comment]
In this file .env
Thanks

**Comment by diouck** [comment]
It's good I solved the problem. Deactivation of the role and nullable role constraint in postgres then paretrage of the mail
Thank you
