### ISSUE TITLE
How to add plugins to ckedit?

### ISSUE THREAD

**Issue by weslings** [bestmomo/laravel5-5-example#26]
How can I add plugins, especially codesnippet, to ckeditor? Even changing the 5.5 with the 5.3 version, in which codesnippet is included, does not work. Do i need to implement it in a view?

**Comment by bestmomo** [comment]
You must load **standard-all** version from CDN.

And in CKEditor config add:
```
config.extraPlugins = 'codesnippet';
```

**Comment by weslings** [comment]
It doesn't work. I took codesnippet inclusive it's dependencies (dialog & widget) in following path:

public/adminlte/plugins/ckeditor/plugins

I then modified config.js located in the ckeditor with

`config.extraPlugins = 'codesnippet';`

with no effect. I also tried

config.extraPlugins = 'dialog,widget,codesnippet';

also with no effect. What am I missing?

**Comment by bestmomo** [comment]
I've tried it on this project and it works for me in editor. I just changed in view:
```
<script src="https://cdn.ckeditor.com/4.7.3/standard-all/ckeditor.js"></script>
```
And in ckeditor.js:
```
CKEDITOR.editorConfig = function( config ) {
    config.extraPlugins = 'codesnippet'
   ...
    config.toolbarGroups = [
        ...
        { name: 'document',	   groups: [ 'mode', 'document', 'doctools' ,'CodeSnippet'] },
       ...
    ]
}
```

**Comment by weslings** [comment]
Thank you, this was the hint I needed.
