### ISSUE TITLE
edit:472 Uncaught TypeError: $.colorbox is not a function

### ISSUE THREAD

**Issue by Romchik** [bestmomo/laravel5-5-example#4]
Admin -> Posts -> Edition
URL: http://test-blog.app/admin/posts/8/edit
Press 'Select an image' in 'Image' block at right column.

Console error:
`edit:472 Uncaught TypeError: $.colorbox is not a function`

**Comment by bestmomo** [comment]
Right,

Corrected in [this commit](https://github.com/bestmomo/laravel5-5-example/commit/936868513f87f19cf1e2268b9ce0ddb5b8fedcae).
