### ISSUE TITLE
Help for a test requete

### ISSUE THREAD

**Issue by GrCOTE7** [bestmomo/laravel5-5-example#6]
Bonjour, BestMomo,

Félicitations pour cette excellent développement et progression dans la maîtrise de laravel :-) !

J'étudie aussi celui-ci et j'en suis à cette étape:

http://laravel.sillo.org/cours-laravel-5-5-les-donnees-la-relation-1n

et en particulier, vers le milieu de la page, la rubrique '**Jouer avec la relation**', là où sont abordés les problèmes de "Lazy" Vs "Eager" loading...

Donc, 

```
$users = User::withCount( 'posts' )
    ->with( [ 'posts' => function ( $query ) {
                                               $query->latest();
                                             }
		    ] )
    ->having( 'posts_count', '>', 0 )
    ->orderBy( 'name', 'asc' )
    ->get();
```

Qui sera bien taduite, quelque soit le nombre d'auteurs concernés, par ces 2 seules et uniques requêtes:

```
select `users`.*, (select count(*) from `posts` where `users`.`id` = `posts`.`user_id`) as `posts_count` from `users` having `posts_count` > '0' order by `name` asc
```
et
```
select * from `posts` where `posts`.`user_id` in ('1', '2', '3') order by `created_at` desc
```

Ceci est bien, mais essayant d'optimiser "l'effet Eager", j'aimerais ne demander que les champs nécessaires.

En effet par exemple, ne reprenant que strictement l'exemple de votre page référée ci-dessus, on a besoin que du champs 'title' des posts...

En conséquence, je m'évertue d'ajouter dans la fonction callback, une ligne :
```
$query->select( 'id', 'title' );
```
Juste au dessus de :
```
$query->latest();
```

Mais, à l'issue, j'observe qu'alors, je n'ai plus du tout les posts... :-(

Grâce à un simple :

```
echo '<pre>';
	var_dump( $users );
echo '</pre>';
```

Le but optimal serait d'avoir la requête suivante:
```
select `id`, `title` from `posts` where `posts`.`user_id` in ('1', '2', '3') order by `created_at` desc
```

À noter que la debugbar nous montre bien qu'on a cette requête pourtant...

Une idée de là où 'ça coince' ;-) ?

Par avance, merci.

**Comment by GrCOTE7** [comment]
Re :-)

Juste pour signaler qu'une solution est celle-ci:

```
$users = User::with( 'posts' )

->with( [ 'posts' => function ( $query ) {
	      $query->select( 'user_id', 'title' );
	      $query->latest();
		}] )
->select('id', 'name', 'email')
->withCount( 'posts' )
->having( 'posts_count', '>', 0 )
->orderBy( 'name', 'asc' )
->get();
```

Ce qui nous permet d'obtenir les 2 seules requêtes précises et optimisées suivantes:

```
select `id`, `name`, `email`, (select count(*)
from `posts`
where `users`.`id` = `posts`.`user_id`) as `posts_count` 
from `users` having `posts_count` > '0' 
order by `name` asc
```

et

```
select `user_id`, `title` from `posts` 
where `posts`.`user_id` in ('1', '2', '3', '5') 
order by `created_at` desc
```



Souhaitant que cela aide d'autres...


Bon WE :-) !

**Comment by bestmomo** [comment]
Salut,

Dans le **select** de la table en relation il faut toujours mentionner la clé étrangère pour que ça fonctionne.

**Comment by GrCOTE7** [comment]
Oui, absolument ! ;-

Merci pour ce suivi :-)

**Comment by bestmomo** [comment]
Le **having** est pas trop joli là, ça serait mieux d'utiliser un **has('posts')**.

**Comment by GrCOTE7** [comment]
Oui, merci pour la critique... :-)

Et outre le fait qu'elle manquait " d'esthétique ", je me suis amusé à tester 1000 boucles sur chacune des versions (L'une avec le 'having...', l'autre avec le 'has...'...

Et au niveau 'tempo', le 'has...' est en plus, préférable (y) ! :-)

Bah, ça ce joue de très peu (Env. 3.4 % d'écart)...

Merci pour l'idée (y)

@++

**Comment by bestmomo** [comment]
Il y a un autre élément à prendre en compte, si tu passes MySQL en mode strict je ne pense pas que le **having** passe bien.
